#
# partial makefile with common variables
# to be included at the beggining of the project's makefile
#

CC ?= clang
DC ?= gdc
AR ?= ar

SRC_DIR := src
OBJ_DIR := obj
LIB_DIR := lib
BIN_DIR := bin
TEST_DIR := tests
